[env]
# FOO = "bar"
# PATH_TO_SOME_TOOL = { value = "bin/tool", relative = true }
# USERNAME = { value = "test_user", force = true }

# Logging is controlled via the RUST_LOG environment variable.
# The value of this environment variable is a comma-separated list of logging directives

# https://docs.rs/env_logger/0.10.0/env_logger/#enabling-logging
RUST_LOG = "rdy2serve,rtc_server,libp2p=debug,libp2p_noise=off,libp2p_webrtc::tokio::udp_mux=off" # libp2p_webrtc::tokio
